name: Deploy Java App to Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clone the repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: ğŸ“ Rename JAR file to app.jar
        run: |
          mkdir -p deploy
          cp target/*.jar deploy/app.jar

      - name: ğŸš€ Copy JAR file to Remote Server via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./deploy/app.jar"
          target: "/opt/java-app/"

      - name: ğŸ›  Restart systemd service on Remote Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl stop app || true
            sudo systemctl start app
